<a href="https://colab.research.google.com/github/nobrainghost/pytorch-deep-learning/blob/main/intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [ ]:
TENSOR.ndim

3

In [18]:
random_tensor=torch.rand(size=[3,244,244],dtype=torch.float16)
random_tensor

tensor([[[0.9424, 0.2817, 0.3257,  ..., 0.7817, 0.8374, 0.8398],
         [0.6475, 0.4160, 0.3604,  ..., 0.4624, 0.8706, 0.4839],
         [0.8735, 0.1528, 0.4316,  ..., 0.6641, 0.0640, 0.2646],
         ...,
         [0.4248, 0.9707, 0.3062,  ..., 0.7524, 0.8359, 0.1479],
         [0.6211, 0.2461, 0.5234,  ..., 0.9951, 0.2661, 0.9966],
         [0.1279, 0.4712, 0.1426,  ..., 0.4780, 0.4399, 0.6758]],

        [[0.5854, 0.3457, 0.0073,  ..., 0.8145, 0.5264, 0.5522],
         [0.2144, 0.6709, 0.9927,  ..., 0.6406, 0.0542, 0.0034],
         [0.3135, 0.7114, 0.7764,  ..., 0.3750, 0.1543, 0.3193],
         ...,
         [0.0293, 0.6606, 0.4473,  ..., 0.8271, 0.9614, 0.9766],
         [0.1089, 0.2915, 0.4072,  ..., 0.3594, 0.4775, 0.6890],
         [0.7407, 0.2124, 0.9873,  ..., 0.1250, 0.8330, 0.0303]],

        [[0.3975, 0.7085, 0.2661,  ..., 0.7192, 0.8047, 0.3892],
         [0.8877, 0.9614, 0.4390,  ..., 0.0098, 0.4878, 0.6367],
         [0.2100, 0.8682, 0.6953,  ..., 0.6733, 0.9019, 0.

In [10]:
rangee=torch.arange(0,1000,100)
rangee
zeroed=torch.zeros_like(input=rangee)
zeroed


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
some_tensor=torch.rand(3,4,2)
some_tensor

tensor([[[0.0080, 0.2537],
         [0.1854, 0.0583],
         [0.7914, 0.2118],
         [0.4353, 0.5745]],

        [[0.2596, 0.0495],
         [0.7473, 0.9760],
         [0.7726, 0.8428],
         [0.2851, 0.4987]],

        [[0.0525, 0.8044],
         [0.0798, 0.0816],
         [0.9441, 0.2879],
         [0.3527, 0.7568]]])

In [23]:
some_tensor.size()

torch.Size([3, 4, 2])

In [24]:
some_tensor.shape

torch.Size([3, 4, 2])

In [25]:
some_tensor.device

device(type='cpu')